### ISSUE TITLE
Practica de Contratos Inteligentes lectura y escritura

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practica-4y5-metztli#1]
[Practica 4y 5 lectura y escritura de contratos inteligentes .pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-metztli/files/8681794/Practica.4y.5.lectura.y.escritura.de.contratos.inteligentes.pdf)

**Comment by uzias10** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
